custom: 
  value: common
spring: 
  jpa: 
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource: 
    url: jdbc:mysql://localhost:3306/society_game?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  data: 
    mongodb: 
      host: localhost
      port: 27017
      database: todos 
---
spring: 
  profiles: dev
custom: 
  value: dev
---
spring: 
  profiles: prod
custom: 
  value: prod
    